### ISSUE TITLE
Dependencies of actual polyfill is added even though actual polyfill is not needed

### ISSUE THREAD

**Issue by byao** [reiniergs/polyfill-service#150]
For example, current Promise polyfill depends on setImmediate. setImmediate polyfill is still returned even though browser (Chrome 58) does not need Promise polyfilled.

Also, look into another Promise polyfill implementation that does not require setImmediate as it is not currently production ready.

**Comment by byao** [comment]
@scottmo @reiniergs

**Comment by scottmo** [comment]
Right. This a bug on service config. Will fix it soon.
