### ISSUE TITLE
Maven Central Repo Registration

### ISSUE THREAD

**Issue by vbhargavmbis** [reiniergs/polyfill-service#159]
Pushing the jar to the maven central repository
- [x] Create a google group
- [x] Figure out which domain name to use
- [x] Register domain 
- [x] File ticket to Jira to get Maven Central's approval
- [x] Ticket Approved!
- [x] Set up and promote first release to central repo
- [x] Push setup code

**Comment by vbhargavmbis** [comment]
[ ] Figure out which domain name to use
[ ] Register domain

**Comment by scottmo** [comment]
Jira Ticket to track registration: https://issues.sonatype.org/browse/OSSRH-32968

**Comment by scottmo** [comment]
Setup has been done by the central ppl. Will promote first release soon

**Comment by scottmo** [comment]
@reiniergs @vbhargavmbis 
Ticket resolved: https://issues.sonatype.org/browse/OSSRH-32968

Central search:
- https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22org.polyfillservice%22
Staging:
- https://oss.sonatype.org/content/groups/staging/org/polyfillservice/
Release:
- https://oss.sonatype.org/content/groups/public/org/polyfillservice/

**Comment by scottmo** [comment]
Will push setup code soon
