### ISSUE TITLE
How close issue by merging PR in github

### ISSUE THREAD

**Issue by reiniergs** [reiniergs/polyfill-service#48]

**Comment by vbhargavmbis** [comment]
We can close an issue when its corresponding PR is merged by using one of the following keywords along with the issue number.
Keywords: 
    close
    closes
    closed
    fix
    fixes
    fixed
    resolve
    resolves
    resolved
Example: fixes #48 OR resolve #48 OR close #48 when this PR is merged

**Comment by reiniergs** [comment]
+1
